#!/usr/bin/env python3
"""Grog container build - stand in for Avalonia's XAML NameGenerator.

The real generator is an MSBuild-plumbed source generator: it needs AdditionalFiles metadata that
bare csc does not supply, so under this pipeline it silently does not run and every code-behind
reference to InitializeComponent() or an x:Name'd control fails to compile.

The recipe's original answer was a hand-written shim. That rots the first time someone adds an
x:Name, and the failure looks like a broken container rather than a stale shim, so this generates
the shim FROM the .axaml instead. Adding a control to the view is enough; nothing here to update.

Emits, for every .axaml that has a .axaml.cs beside it:
  - partial class <x:Class> { private void InitializeComponent() => AvaloniaXamlLoader.Load(this); }
  - one lazy FindControl property per x:Name on that view

Properties, not fields: the real generator assigns fields during InitializeComponent, but a lazy
lookup is equivalent for everything the code-behind does and cannot go stale against load order.
Names inside DataTemplates resolve to null if ever touched, exactly as FindControl would.
"""
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

# Element local-name -> CLR type, for the few controls that do not live in Avalonia.Controls.
# Everything else is assumed to be Avalonia.Controls.<LocalName>; if that is wrong the compiler
# says so by name and the fix is one line here.
TYPE_OVERRIDES = {
    "DataGrid": "Avalonia.Controls.DataGrid",
    "Window": "Avalonia.Controls.Window",
    "NativeMenu": "Avalonia.Controls.NativeMenu",
    # Primitives, not Controls. Getting this wrong produces a CS0234 that names the type, so the
    # fix is always one line here.
    "Popup": "Avalonia.Controls.Primitives.Popup",
    "Thumb": "Avalonia.Controls.Primitives.Thumb",
    "ScrollBar": "Avalonia.Controls.Primitives.ScrollBar",
    "TabStrip": "Avalonia.Controls.Primitives.TabStrip",
    "ToggleButton": "Avalonia.Controls.Primitives.ToggleButton",
    "TextPresenter": "Avalonia.Controls.Presenters.TextPresenter",
    "ContentPresenter": "Avalonia.Controls.Presenters.ContentPresenter",
    "ItemsPresenter": "Avalonia.Controls.Presenters.ItemsPresenter",
    "ScrollContentPresenter": "Avalonia.Controls.Presenters.ScrollContentPresenter",
}

XAML_NS = "{http://schemas.microsoft.com/winfx/2006/xaml}"


def clr_type(tag: str) -> str:
    local = tag.split("}")[-1]
    if "." in local:                      # attached-property element, never a control
        return ""
    return TYPE_OVERRIDES.get(local, f"Avalonia.Controls.{local}")


def emit(axaml: Path) -> str:
    text = axaml.read_text(encoding="utf-8")
    m = re.search(r'x:Class="([^"]+)"', text)
    if not m:
        return ""
    full = m.group(1)
    ns, _, cls = full.rpartition(".")

    root = ET.parse(axaml).getroot()
    props: dict[str, str] = {}
    for el in root.iter():
        name = el.attrib.get(XAML_NS + "Name")
        if not name or name in props:
            continue
        t = clr_type(el.tag)
        if t:
            props[name] = t

    # BLOCK namespaces, not file-scoped. Every view's shim lands in ONE generated file, and a file
    # may hold at most one file-scoped namespace (CS8954). Worse than the error itself: the parse
    # goes wrong quietly enough that later namespaces nest, and the compiler then reports dozens of
    # CS0234s about types like Grog.App.Grog.Core in files that are perfectly fine.
    body = [
        "// GENERATED by tools/container-build/gen-name-shim.py - do not edit, do not commit.",
        f"namespace {ns}",
        "{",
        # FindControl<T> is an EXTENSION method (Avalonia.Controls.NameScopeExtensions), so fully
        # qualifying the control types is not enough - the namespace has to be in scope for the
        # extension to bind at all.
        "    using Avalonia.Controls;",
        "",
        f"    public partial class {cls}",
        "    {",
        "        private void InitializeComponent() =>",
        "            Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(this);",
    ]
    for name, t in sorted(props.items()):
        body.append(f'        internal {t} {name} => this.FindControl<{t}>("{name}")!;')
    body.append("    }")
    body.append("}")
    body.append("")
    return "\n".join(body)


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: gen-name-shim.py <projectDir> <outFile>", file=sys.stderr)
        return 2
    project, out = Path(sys.argv[1]), Path(sys.argv[2])

    chunks = []
    for axaml in sorted(project.rglob("*.axaml")):
        if "_to_delete" in axaml.parts or "obj" in axaml.parts or "bin" in axaml.parts:
            continue
        if not axaml.with_suffix(".axaml.cs").exists():
            continue                      # no code-behind, nothing to satisfy
        chunk = emit(axaml)
        if chunk:
            chunks.append(chunk)

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(chunks), encoding="utf-8")
    print(f"name shim: {out} ({len(chunks)} views)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
